stages:
  - test
  - deploy

cache:
  paths:
  - node_modules/

cypress:
  stage: test
  image: cypress/base:11.13.0
  variables:
    NODE_ENV: "development"
  script:
    - npm i
    - npx next build
    - npx next start
    - npx cypress run
  artifacts:
    paths:
      - cypress/videos
    expire_in: 1 day