stages:
  - test
  - deploy
  - test_staging

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  # key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

cypress:
  stage: test
  image: cypress/browsers:node11.13.0-chrome73
  variables:
    NODE_ENV: "development"
  script:
    - npm i --silent
    - npx next build
    - npx next start & npx wait-on http://localhost:3000
    - npx cypress run
  artifacts:
    reports:
      junit: results/*.xml
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 week

deploy_staging:
  stage: deploy
  image: node:11.14.0
  only:
    - master
  variables:
    NODE_ENV: "production"
  script:
    - npm i -g now@14.0.3 --silent --unsafe-perm
    - now alias $(now --token=$NOW_TOKEN) staging.apex-legends.win --token=$NOW_TOKEN

deploy_prod:
  stage: deploy
  image: node:11.14.0
  only:
    - tags
  when: manual
  allow_failure: false
  variables:
    NODE_ENV: "production"
  script:
    - npm i -g now@14.0.3 --silent --unsafe-perm
    - now alias $(now --token=$NOW_TOKEN) staging.apex-legends.win --token=$NOW_TOKEN

test_staging:
  stage: test_staging
  image: cypress/browsers:node11.13.0-chrome73
  script:
    # check cypress (without npx) if fails, otherwise run npm i before test
    - npx cypress run --config baseUrl=https://staging.apex-legends.win
  artifacts:
    reports:
      junit: results/*.xml
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 week