stages:
  - test
  - deploy

cache:
  paths:
  - node_modules/
  - .cache/Cypress

cypress:
  stage: test
  image: cypress/base:11.13.0
  only:
    - disabled
  variables:
    NODE_ENV: "development"
  script:
    - npm i --silent
    - npx next build
    - npm run start:ci
  artifacts:
    paths:
      - cypress/videos
    expire_in: 1 day

deploy_staging:
  stage: deploy
  image: node:11.14.0
  script:
    - echo $NOW_TOKEN
    - npm i -g now --silent --unsafe-perm
    - now alias $(now --token=$NOW_TOKEN) staging.apex-legends.win --token=$NOW_TOKEN

deploy_prod:
  stage: deploy
  image: node:11.14.0
  only:
    - tags
  when: manual
  allow_failure: false
  script:
    - npm i -g now --silent --unsafe-perm
    - now alias $(now --token="$NOW_TOKEN") staging.apex-legends.win --token="$NOW_TOKEN"